version: '3.6'
services:
  remote-controller:
    image: docker.pkg.github.com/juliansauer/remotecontroller/remote-controller:latest
    restart: always
    ports:
      - 8080:8080
	volumes:
      - ${PWD}/config.json://go/src/github.com/JulianSauer/RemoteController/config.json
      - ${PWD}/remote.json://go/src/github.com/JulianSauer/RemoteController/remote.json
