name: Build and Deploy

on:
  push:
    branches:
    - master

env:
  USER_GITHUB: JulianSauer
  USER_DOCKER_HUB: juliansauer
  TOKEN_GITHUB: ${{ secrets.PACKAGE_TOKEN }}
  TOKEN_DOCKER_HUB: ${{ secrets.DOCKER_HUB_TOKEN }}
  REGISTRY:  docker.pkg.github.com/juliansauer/remotecontroller
  IMAGE: remote-controller
  TAG: latest

jobs:
  setup-build-publish-deploy:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    # Build the Docker image
    - name: Build
      run: docker build -t "$IMAGE":"$GITHUB_SHA" .

    # Push the Docker image to Github Container Registry and DockerHub
    - name: Publish
      run: |
        docker login docker.pkg.github.com --username "$USER_GITHUB" -p "$TOKEN_GITHUB"
        docker tag "$IMAGE":"$GITHUB_SHA" "$REGISTRY"/"$IMAGE":"$GITHUB_SHA"
        docker tag "$IMAGE":"$GITHUB_SHA" "$REGISTRY"/"$IMAGE":"$TAG"
        docker push "$REGISTRY"/"$IMAGE":"$GITHUB_SHA"
        docker push "$REGISTRY"/"$IMAGE":"$TAG"
        docker login --username "$USER_DOCKER_HUB" -p "$TOKEN_DOCKER_HUB"
        docker tag "$IMAGE":"$GITHUB_SHA" "$USER_DOCKER_HUB"/"$IMAGE":"$GITHUB_SHA"
        docker tag "$IMAGE":"$GITHUB_SHA" "$USER_DOCKER_HUB"/"$IMAGE":"$TAG"
        docker push "$USER_DOCKER_HUB"/"$IMAGE":"$GITHUB_SHA"
        docker push "$USER_DOCKER_HUB"/"$IMAGE":"$TAG"
